version: 2

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: "{{ .Tag }}"
checksum:
  name_template: "checksums.txt"

builds:
  - id: build
    binary: tblocker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}

archives:
  - id: torrent-blocker
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - config.yaml.default

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
  name_template: "v{{ .Version }}"

nfpms:
  - id: tblocker
    package_name: tblocker
    maintainer: Sergey Kutov <sergey@kutovoy.dev>
    description: Xray Torrent Blocker
    homepage: https://github.com/kutovoys/xray-torrent-blocker
    license: AGPL-3.0
    formats: [deb, rpm]
    bindir: /opt/tblocker
    contents:
      - src: config.yaml.default
        dst: /opt/tblocker/config.yaml
        type: config|noreplace
      - src: tblocker.service
        dst: /etc/systemd/system/tblocker.service
        type: config
    scripts:
      postinstall: ./scripts/postinstall.sh
      preremove: ./scripts/preremove.sh
      postremove: ./scripts/postremove.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
